---
apiVersion: v1
kind: Service
metadata:
  name: results-app-service
  labels:
    author: burgula
spec:
  type: LoadBalancer
  ports:
    - targetPort: 80
      port: 80
      nodePort: 30008
  selector:
    name: results-app

...