---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: results-app-deployment
  labels:
    name: result-app
    author: burgula
spec:
  replicas: 2
  selector:
    matchLabels:
      name: result-app
  template:
    metadata:
      name: results-app-pod
      labels:
        name: results-app
    spec:
      containers:
        - name: results-app
          image: dockersamples/examplevotingapp_result

...